// Generated by gencpp from file turtlebot_msgs/GoalPose.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_MSGS_MESSAGE_GOALPOSE_H
#define TURTLEBOT_MSGS_MESSAGE_GOALPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace turtlebot_msgs
{
template <class ContainerAllocator>
struct GoalPose_
{
  typedef GoalPose_<ContainerAllocator> Type;

  GoalPose_()
    : header()
    , x(0.0)
    , y(0.0)
    , speed(0.0)
    , heading(0.0)
    , max_speed(0.0)
    , max_accel(0.0)  {
    }
  GoalPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , speed(0.0)
    , heading(0.0)
    , max_speed(0.0)
    , max_accel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _max_speed_type;
  _max_speed_type max_speed;

   typedef double _max_accel_type;
  _max_accel_type max_accel;





  typedef boost::shared_ptr< ::turtlebot_msgs::GoalPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_msgs::GoalPose_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPose_

typedef ::turtlebot_msgs::GoalPose_<std::allocator<void> > GoalPose;

typedef boost::shared_ptr< ::turtlebot_msgs::GoalPose > GoalPosePtr;
typedef boost::shared_ptr< ::turtlebot_msgs::GoalPose const> GoalPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_msgs::GoalPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'turtlebot_msgs': ['/home/suraj/Turtlebot-3-Navigation/catkin_ws/src/turtlebot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_msgs::GoalPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_msgs::GoalPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_msgs::GoalPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b41ed743e7940944d509142a63f050aa";
  }

  static const char* value(const ::turtlebot_msgs::GoalPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb41ed743e7940944ULL;
  static const uint64_t static_value2 = 0xd509142a63f050aaULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_msgs/GoalPose";
  }

  static const char* value(const ::turtlebot_msgs::GoalPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 x\n\
float64 y\n\
float64 speed\n\
float64 heading\n\
float64 max_speed\n\
float64 max_accel\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::turtlebot_msgs::GoalPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.speed);
      stream.next(m.heading);
      stream.next(m.max_speed);
      stream.next(m.max_accel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_msgs::GoalPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_msgs::GoalPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "max_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_speed);
    s << indent << "max_accel: ";
    Printer<double>::stream(s, indent + "  ", v.max_accel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_MSGS_MESSAGE_GOALPOSE_H
